[package]
name = "spvn_caller"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
documentation.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"
license = "MIT"

[lib]

[dependencies]
async-trait = {version = "0.1.68"}

libc = { version = "0.2.144" }
cpython = { version = "0.7", features = ["python3-sys"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simple_logger = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
colored = { version = "2.0.0" }
