[package]
name = "spvn_caller"
version = { workspace = true }
publish = false
edition = { workspace = true }
rust-version = { workspace = true }
crate-type = ["cdylib"]

[lib]


[dependencies]
async-trait = {version = "0.1.68"}

libc = { version = "0.2.144" }
cpython = { version = "0.7", features = ["python3-sys"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simple_logger = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
colored = { version = "2.0.0" }
