[workspace]
members = ["crates/*"]


[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.69.0"
authors = ["Joshua A. <joshua.auchincloss@proton.me>"]


[workspace.dependencies]
pyo3 = {version = "0.18.3", features = ["extension-module"]}
serde = { version = "1.0", features = ["derive"] }
pythonize = { version = "0.18.0" }
tokio = {version = "1.9", features = ["sync"]}
async-trait = {version = "0.1.68"}
simple_logger = "4.1.0"

