[package]
name = "spvn_cfg"
version = { workspace = true }
publish = false
edition = { workspace = true }
rust-version = { workspace = true }

[lib]
crate-type = ["rlib"]

[dependencies]
tokio-rustls = "0.24"
rustls-pemfile = "1.0"
