[package]
name = "spvn_serde"
version = { workspace = true }
publish = false
edition = { workspace = true }



[dependencies]
cpython = { workspace = true, features = ["python3-sys"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"