[package]
name = "spvn_serde"
version = { workspace = true }
publish = false
edition = { workspace = true }

[lib]
crate-type = ["rlib"]


[dependencies]
pyo3 = {workspace = true}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = {workspace = true}