[package]
name = "spvn"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
documentation.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"
license = "MIT"

[lib]
name = "spvn"

[dependencies]
spvn_caller = {path = "../spvn_caller"}
tokio-rustls = "0.23"
tokio = { workspace = true, features = ["sync", "macros"] }
rustls-pemfile = "0.3"
hyper = { workspace = true, features = ["full"] }
http = { workspace = true }
futures = { version = "0.3.28" }
tower = {workspace = true, features = ["make", "timeout"]}
tower-layer = { version = "0.3.2" }
tower-service = { version = "0.3.2" }
