[package]
name = "spvn_log"
version = { workspace = true }
publish = false
edition = { workspace = true }
rust-version = { workspace = true }

[lib]
crate-type = ["proc-macro"]

[dependencies]
simple_logger = { workspace = true }
log = { workspace = true }
colored = { workspace = true }
